#!/bin/bash
# Delete regenerable build artifacts to reclaim disk space. Run via
# `make clean`, or directly: scripts/clean.sh [--dry-run] [--app]
# [--models] [--global].
#
# Default targets: .build/ in the root and every package (benchmark/,
# experiments/*) plus stray .DS_Store files. pfeifer.app and models/ are
# kept by default — the app bundle is the runnable product, and the model
# weights are a manual ~GB re-download; both have opt-in flags. Never
# touched: Package.resolved (pins dependencies), benchmark/clips/ (personal
# recordings), sources, docs, .git.
#
# Deleting .build/ makes the next `swift build` a full rebuild — this
# is the same clean AGENTS.md prescribes after every CLT update.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GLOBAL_CACHE="$HOME/Library/Caches/org.swift.swiftpm"

DRY_RUN=0
WITH_APP=0
WITH_MODELS=0
WITH_GLOBAL=0

usage() {
  cat <<EOF
usage: scripts/clean.sh [--dry-run] [--app] [--models] [--global]

  --dry-run   print what would be deleted (with sizes); delete nothing
  --app       also delete pfeifer.app (regenerated by 'make app')
  --models    also delete models/ (asks first — the Parakeet weights
              are a ~GB re-download)
  --global    also delete ~/Library/Caches/org.swift.swiftpm (SwiftPM's
              shared cache, used by every project on this machine)
EOF
}

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --app) WITH_APP=1 ;;
    --models) WITH_MODELS=1 ;;
    --global) WITH_GLOBAL=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown option: $arg" >&2; usage >&2; exit 1 ;;
  esac
done

kb_of() { # path -> size in KB (du -sk), 0 when absent
  if [[ -e "$1" ]]; then
    du -sk "$1" | cut -f1
  else
    echo 0
  fi
}

human() { # KB -> "1.6 GB" / "881 MB" / "64 KB"
  local kb="$1"
  if (( kb >= 1048576 )); then
    printf '%d.%d GB' $((kb / 1048576)) $(((kb % 1048576) * 10 / 1048576))
  elif (( kb >= 1024 )); then
    printf '%d MB' $((kb / 1024))
  else
    printf '%d KB' "$kb"
  fi
}

RECLAIMED_KB=0

remove_target() { # path description
  local path="$1" what="$2"
  [[ -e "$path" ]] || return 0
  local kb
  kb="$(kb_of "$path")"
  RECLAIMED_KB=$((RECLAIMED_KB + kb))
  if [[ $DRY_RUN -eq 1 ]]; then
    printf '[dry-run] would delete %s: %s (%s)\n' "$what" "$path" "$(human "$kb")"
  else
    rm -rf "$path"
    printf 'deleted %s: %s (%s)\n' "$what" "$path" "$(human "$kb")"
  fi
}

# models/ is a real re-download, so confirm outside dry-run.
if [[ $WITH_MODELS -eq 1 && $DRY_RUN -eq 0 && -d "$ROOT/models" ]]; then
  echo "models/ holds the downloaded Parakeet weights ($(human "$(kb_of "$ROOT/models")"))."
  echo "Deleting them means re-downloading later — hundreds of MB to ~2 GB."
  reply=""
  read -r -p "Delete models/? [y/N] " reply || true
  if [[ "$reply" == "y" || "$reply" == "Y" ]]; then
    echo "models/ will be deleted"
  else
    echo "keeping models/"
    WITH_MODELS=0
  fi
fi

remove_target "$ROOT/.build" "SwiftPM build dir"
remove_target "$ROOT/benchmark/.build" "SwiftPM build dir"

# Every standalone package under experiments/ has its own .build.
if [[ -d "$ROOT/experiments" ]]; then
  while IFS= read -r dir; do
    [[ -n "$dir" ]] && remove_target "$dir" "SwiftPM build dir"
  done < <(find "$ROOT/experiments" -mindepth 2 -maxdepth 2 -type d -name .build)
fi

if [[ $WITH_APP -eq 1 ]]; then
  remove_target "$ROOT/pfeifer.app" "app bundle"
fi
if [[ $WITH_MODELS -eq 1 ]]; then
  remove_target "$ROOT/models" "model weights"
fi
if [[ $WITH_GLOBAL -eq 1 ]]; then
  remove_target "$GLOBAL_CACHE" "SwiftPM global cache"
fi

# Finder metadata anywhere in the repo, .git excluded.
ds_count=0
ds_kb=0
while IFS= read -r f; do
  ds_count=$((ds_count + 1))
  ds_kb=$((ds_kb + ($(stat -f%z "$f") + 1023) / 1024))
  if [[ $DRY_RUN -ne 1 ]]; then
    rm -f "$f"
  fi
done < <(find "$ROOT" -name .git -prune -o -name .DS_Store -print)

if [[ $ds_count -gt 0 ]]; then
  RECLAIMED_KB=$((RECLAIMED_KB + ds_kb))
  if [[ $DRY_RUN -eq 1 ]]; then
    printf '[dry-run] would delete %d .DS_Store file(s) (%s)\n' "$ds_count" "$(human "$ds_kb")"
  else
    printf 'deleted %d .DS_Store file(s) (%s)\n' "$ds_count" "$(human "$ds_kb")"
  fi
fi

if [[ $RECLAIMED_KB -eq 0 ]]; then
  echo "nothing to clean"
elif [[ $DRY_RUN -eq 1 ]]; then
  echo "dry-run: nothing deleted; would reclaim ~$(human "$RECLAIMED_KB")"
else
  echo "reclaimed ~$(human "$RECLAIMED_KB")"
fi
